apiVersion: v1
kind: PersistentVolume
metadata:
  name: prom-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.27.20.135:6789
      - 10.27.20.136:6789
      - 10.27.20.137:6789
    path: /enos/prometheus
    user: prometheus
    secretRef:
      name: cephfs-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
