apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
    - name: digits-container
      image: nvidia/digits:6.0
      resources:
        limits:
#          alpha.kubernetes.io/nvidia-gpu: 2
          nvidia.com/gpu: 3 # requesting 2 GPUs
