apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
subsets:
- addresses:
  - ip: 10.27.20.82
    targetRef:
      kind: Node
      name: k8s8001
  - ip: 10.27.20.83
    targetRef:
      kind: Node
      name: k8s8002
  - ip: 10.27.20.84
    targetRef:
      kind: Node
      name: k8s8003
  ports:
  - name: http-metrics
    port: 10251
    protocol: TCP
