apiVersion: v1
kind: Service
metadata:
#  annotations:
#    prometheus.io/port: "9153"
#    prometheus.io/scrape: "true"
  labels:
    k8s-app: ingress-nginx-exporter
#    kubernetes.io/cluster-service: "true"
#    kubernetes.io/name: ingress-nginx-exporter
  name: ingress-nginx-exporter
  namespace: ingress-nginx
spec:
  ports:
#  - name: ingress-tcp
#    port: 10254
#    protocol: TCP
#    targetPort: 10254
  - name: http-metrics
    port: 10254
#    protocol: TCP
#    targetPort: 10254
  selector:
    app.kubernetes.io/name: ingress-nginx
#    app.kubernetes.io/part-of: ingress-nginx
  type: ClusterIP
